name: Build gpsp

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

    - name: Build
      run: |
        export CC=arm-linux-gnueabihf-gcc
        export CXX=arm-linux-gnueabihf-g++
        export AR=arm-linux-gnueabihf-ar
        export CFLAGS="-Ofast -flto=4 -fwhole-program -fuse-linker-plugin -fdata-sections -ffunction-sections -Wl,--gc-sections -fno-stack-protector -fno-ident -fomit-frame-pointer -falign-functions=1 -falign-jumps=1 -falign-loops=1 -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-unroll-loops -fmerge-all-constants -fno-math-errno -marm -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard"
        export CXXFLAGS="$CFLAGS -std=gnu++11"
        export CPPFLAGS="$CFLAGS"
        export ASFLAGS="$CFLAGS"
        make platform=unix-armv7-hardfloat-neon HAVE_NEON=1 MMAP_JIT_CACHE=1 HAVE_DYNAREC=1 ARCH=arm BUILTIN_GPU=neon fpic=-fPIC SHARED="-shared -Wl,--version-script=link.T -Wl,--no-undefined"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gpsp-libretro
        path: gpsp_libretro.so
